import type { Metadata } from "next";
import "./globals.css";
import { PhoneArrowUpRight, ShoppingCart } from "../../public/svg/svg";
import HambrgerMenue from "../../components/ui/HambrgerMenue";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`/50 w-screen h-screen font-Dana-medium`}
      >
            
        {children}
      </body>
    </html>
  );
};
